# Generated by Django 4.2.6 on 2023-11-10 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FartiModel',
            fields=[
                ('map_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Map.mapmodel')),
                ('dan', models.IntegerField()),
                ('mde', models.IntegerField()),
                ('otaxebisRaodenoba', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FasiModel',
            fields=[
                ('map_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Map.mapmodel')),
                ('dan', models.IntegerField()),
                ('mde', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MdebareobaModel',
            fields=[
                ('map_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Map.mapmodel')),
                ('mdebareoba', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StatusiModel',
            fields=[
                ('map_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Map.mapmodel')),
                ('chabarebuli', models.BooleanField(default=False)),
                ('mshenebare', models.BooleanField(default=False)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='mapmodel',
            name='farti',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Map.fartimodel'),
        ),
        migrations.AddField(
            model_name='mapmodel',
            name='fasi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Map.fasimodel'),
        ),
        migrations.AddField(
            model_name='mapmodel',
            name='mdebareoba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Map.mdebareobamodel'),
        ),
        migrations.AddField(
            model_name='mapmodel',
            name='statusi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Map.statusimodel'),
        ),
    ]
