# Generated by Django 4.2.6 on 2023-11-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdebareobamodel',
            name='lat',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mdebareobamodel',
            name='lng',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
