# Generated by Django 4.2.6 on 2023-11-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0002_mdebareobamodel_lat_mdebareobamodel_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='fartimodel',
            name='kvadratuli_farti',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
